'\" t
.\"     Title: pcp_recovery_node
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: pgpool-II 3.6.4 Documentation
.\"    Source: pgpool-II 3.6.4
.\"  Language: English
.\"
.TH "PCP_RECOVERY_NODE" "1" "2016" "pgpool-II 3.6.4" "pgpool-II 3.6.4 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pcp_recovery_node \- attaches the given backend node with recovery
.SH "SYNOPSIS"
.HP \w'\fBpcp_recovery_node\fR\ 'u
\fBpcp_recovery_node\fR [\fIoptions\fR...] [\fInode_id\fR]
.SH "DESCRIPTION"
.PP
\fBpcp_node_info\fR
attaches the given backend node with recovery\&.
.SH "OPTIONS"
.PP
.PP
\fB\-n \fR\fB\fInode_id\fR\fR
.br
\fB\-\-node\-id=\fR\fB\fInode_id\fR\fR
.RS 4
The index of backend node\&.
.RE
.PP
\fBOther options \fR
.RS 4
See
\fBpcp_common_options\fR(1)\&.
.RE
