'\" t
.\"     Title: pcp_pool_status
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: pgpool-II 3.6.4 Documentation
.\"    Source: pgpool-II 3.6.4
.\"  Language: English
.\"
.TH "PCP_POOL_STATUS" "1" "2016" "pgpool-II 3.6.4" "pgpool-II 3.6.4 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pcp_pool_status \- displays the parameter values as defined in pgpool\&.conf
.SH "SYNOPSIS"
.HP \w'\fBpcp_pool_status\fR\ 'u
\fBpcp_pool_status\fR [\fIoptions\fR...]
.SH "DESCRIPTION"
.PP
\fBpcp_pool_status\fR
displays the parameter values as defined in
pgpool\&.conf\&.
.SH "OPTIONS"
.PP
See
\fBpcp_common_options\fR(1)\&.
.SH "EXAMPLE"
.PP
Here is an example output:
.sp
.if n \{\
.RS 4
.\}
.nf
$ pcp_pool_status \-h localhost \-U postgres
name : listen_addresses
value: localhost
desc : host name(s) or IP address(es) to listen to

name : port
value: 9999
desc : pgpool accepting port number

name : socket_dir
value: /tmp
desc : pgpool socket directory

name : pcp_port
value: 9898
desc : PCP port # to bind
    
.fi
.if n \{\
.RE
.\}
.sp

