'\" t
.\"     Title: SHOW POOL_POOLS
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: pgpool-II 3.6.4 Documentation
.\"    Source: pgpool-II 3.6.4
.\"  Language: English
.\"
.TH "SHOW POOL_POOLS" "1" "2016" "pgpool-II 3.6.4" "pgpool-II 3.6.4 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
SHOW_POOL_POOLS \- sends back a list of pools handled by Pgpool\-II\&.
.SH "SYNOPSIS"
.sp
.nf
SHOW POOL_POOLS
    
.fi
.SH "DESCRIPTION"
.PP
\fBSHOW POOL_POOLS\fR
sends back a list of pools handled by
Pgpool\-II
.PP
It has 11 columns:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_pid
is the PID of the displayed
Pgpool\-II
process\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start_time
is the timestamp of when this process was launched\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_id
is the pool identifier (should be between 0 and
max_pool
\- 1)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
backend_id
is the backend identifier (should be between 0 and the number of configured backends minus one)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
database
is the database name for this process\*(Aqs pool id connection\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
username
is the user name for this process\*(Aqs pool id connection\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
create_time
is the creation time and date of the connection\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
majorversion
and
minorversion
are the protocol version numbers used in this connection\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_counter
counts the number of times this pool of connections (process) has been used by clients\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_backendpid
is the PID of the PostgreSQL process\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_connected
is true (1) if a frontend is currently using this backend\&.
.RE
.PP
It\*(Aqll always return
num_init_children
*
max_pool
* number_of_backends lines\&. Here is an example session:
.sp
.if n \{\
.RS 4
.\}
.nf
test=# show pool_pools;
 pool_pid |     start_time      | pool_id | backend_id | database | username |     create_time     | majorversion | minorversion | pool_counter | pool_backendpid | pool_connected
\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 19696    | 2016\-10\-17 13:24:17 | 0       | 0          | postgres | t\-ishii  | 2016\-10\-17 13:35:12 | 3            | 0            | 1            | 20079           | 1
 19696    | 2016\-10\-17 13:24:17 | 0       | 1          | postgres | t\-ishii  | 2016\-10\-17 13:35:12 | 3            | 0            | 1            | 20080           | 1
 19696    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 0       | 0          | test     | t\-ishii  | 2016\-10\-17 14:30:53 | 3            | 0            | 1            | 22055           | 1
 20024    | 2016\-10\-17 13:33:46 | 0       | 1          | test     | t\-ishii  | 2016\-10\-17 14:30:53 | 3            | 0            | 1            | 22056           | 1
 20024    | 2016\-10\-17 13:33:46 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
(256 rows)
.fi
.if n \{\
.RE
.\}
.sp

