'\" t
.\"     Title: pcp_recovery_node
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: Pgpool-II 3.6.4 文書
.\"    Source: Pgpool-II 3.6.4
.\"  Language: Japanese
.\"
.TH "PCP_RECOVERY_NODE" "1" "2016" "Pgpool-II 3.6.4" "Pgpool-II 3.6.4 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
pcp_recovery_node \- Pgpool\-II のノードのデータを再同期させた上で復帰させる
.SH "概要"
.HP \w'\fBpcp_recovery_node\fR\ 'u
\fBpcp_recovery_node\fR [\fIoptions\fR...] [\fInode_id\fR]
.SH "説明"
.PP
\fBpcp_node_info\fR
は
Pgpool\-II
のノードのデータを再同期させた上で復帰させます。
.SH "オプション"
.PP
.PP
\fB\-n \fR\fB\fInode_id\fR\fR
.br
\fB\-\-node\-id=\fR\fB\fInode_id\fR\fR
.RS 4
バックエンドノードのインデックスを指定します。
.RE
.PP
\fBその他 \fR
.RS 4
\fBpcp_common_options\fR(1)
を参照してください。
.RE
