'\" t
.\"     Title: pgpool_setup
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: Pgpool-II 3.6.4 文書
.\"    Source: Pgpool-II 3.6.4
.\"  Language: Japanese
.\"
.TH "PGPOOL_SETUP" "1" "2016" "Pgpool-II 3.6.4" "Pgpool-II 3.6.4 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
pgpool_setup \- Pgpool\-II クラスタのテスト環境を構築するツール
.SH "概要"
.HP \w'\fBpgpool_setup\fR\ 'u
\fBpgpool_setup\fR [\fIoption\fR...]
.SH "説明"
.PP
pgpool_setup
はカレントディレクトリで
Pgpool\-II
とノード数が指定できる複数の
PostgreSQL
のクラスタテスト環境を構築するツールです。 カレントディレクトリは空である必要があります。
.PP
pgpool_setup
はテストのために使うツールなので、 実際の業務システムで利用することはおすすめしません。
.PP
現在、「ストリーミングレプリケーションモード」、「ネイティブレプリケーションモード」及び「raw モード」に対応しています。 Watchdog の対応については
\fBwatchdog_setup\fR(1)
をご参照下さい。
.SH "オプション"
.PP
pgpool_setup
以下のコマンドライン引数を受け付けます:
.PP
\fB\-m \fR\fB\fImode\fR\fR
.RS 4
動作モードを指定します。\fImode\fRは
r
(ネイティブレプリケーションモード),
s
(ストリーミングレプリケーションモード)、または
n
(raw モード)を指定できます。 指定しない場合は、s
(ストリーミングレプリケーションモード) です。
.RE
.PP
\fB\-n \fR\fB\fInum_clusters\fR\fR
.RS 4
PostgreSQL のノード数を指定します。指定しない場合は、ノード数が 2 です。
.RE
.PP
\fB\-p \fR\fB\fIbase_port\fR\fR
.RS 4
ベースとなるポート番号を指定します。 Pgpool\-II のポートは base_port、pcp のポートは base_port + 1、 最初の PostgreSQL ノードのポートは base_port + 2、 2 番目の PostgreSQL ノードのポートは base_port + 3 というようになります。
.sp
\-pg オプションを指定した場合、 最初の PostgreSQL ノードのポートは pg_base_port、 2 番目の PostgreSQL ノードのポートは pg_base_port + 1 というように割り当てていきます。
.sp
指定しない場合、ベースとなるポート番号は 11000 です。
.RE
.PP
\fB\-pg \fR\fB\fIpg_base_port\fR\fR
.RS 4
PostgreSQL のベースとなるポート番号を指定します。 最初の PostgreSQL ノードのポートは base_port + 2、 2 番目の PostgreSQL ノードのポートは base_port + 3 というようになります。
.sp
省略した場合は、
base_port+2 が使われます。
.RE
.PP
\fB\-\-no\-stop\fR
.RS 4
セットアップ終了後に
Pgpool\-II, PostgreSQL を終了しません。
.RE
.PP
\fB\-d\fR
.RS 4
デバッグモードで
Pgpool\-II
を起動します。
.RE
.SH "環境変数"
.PP
pgpool_setup
以下の環境変数を使用します:
.PP
\fBPGPOOL_INSTALL_DIR\fR
.RS 4
Pgpool\-II
のインストールディレクトリを指定します。
Pgpool\-II
バイナリーは PGPOOL_INSTALL_DIR/bin ディレクトリ以下、
pgpool\&.conf
と
pool_hba\&.conf
などは PGPOOL_INSTALL_DIR/etc ディレクトリ以にインストールされます。 デフォルトでは /usr/local ディレクトリ以下にインストールされます。
.RE
.PP
\fBPGPOOLDIR\fR
.RS 4
Pgpool\-II
設定ファイルへのパスを指定します。 デフォルトでは PGPOOL_INSTALL_DIR/etc です。
.RE
.PP
\fBPGBIN\fR
.RS 4
initdb、pg_ctl と psql など
PostgreSQL
コマンドへのパスを指定します。 デフォルトでは、/usr/local/pgsql/bin です。
.RE
.PP
\fBPGLIB\fR
.RS 4
PostgreSQL
の共有ライブラリへのパスを指定します。 デフォルトでは、/usr/local/pgsql/lib です。
.RE
.PP
\fBPGSOCKET_DIR\fR
.RS 4
Unixソケットのディレクトリへのパスを指定します。 デフォルトでは /tmp です。
.RE
.PP
\fBINITDBARG\fR
.RS 4
initdb コマンドの引数を指定します。 デフォルトでは "\-\-no\-locale \-E UTF_8" です。
.RE
.SH "出力例"
.PP
.if n \{\
.RS 4
.\}
.nf
$ pgpool_setup
Satrting set up in streaming replication mode
creating startall and shutdownall
creating failover script
creating database cluster /home/t\-ishii/tmp/test/data0\&.\&.\&.done\&.
update postgreql\&.conf
creating pgpool_remote_start
creating basebackup\&.sh
creating recovery\&.conf
creating database cluster /home/t\-ishii/tmp/test/data1\&.\&.\&.done\&.
update postgreql\&.conf
creating pgpool_remote_start
creating basebackup\&.sh
creating recovery\&.conf
temporarily start data0 cluster to create extensions
temporarily start pgpool\-II to create standby nodes
INFO:  unrecognized configuration parameter "debug_level"
 node_id | hostname | port  | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay
\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 0       | /tmp     | 11002 | up     | 0\&.500000  | primary | 0          | true              | 0
 1       | /tmp     | 11003 | down   | 0\&.500000  | standby | 0          | false             | 0
(2 rows)

recovery node 1\&.\&.\&.pcp_recovery_node \-\- Command Successful
done\&.
creating follow master script
Pager usage is off\&.
 node_id | hostname | port  | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay
\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 0       | /tmp     | 11002 | up     | 0\&.500000  | primary | 0          | false             | 0
 1       | /tmp     | 11003 | up     | 0\&.500000  | standby | 0          | true              | 0
(2 rows)

shutdown all

pgpool\-II setting for streaming replication mode is done\&.
To start the whole system, use /home/t\-ishii/tmp/test/startall\&.
To shutdown the whole system, use /home/t\-ishii/tmp/test/shutdownall\&.
pcp command user name is "t\-ishii", password is "t\-ishii"\&.
Each PostgreSQL, pgpool\-II and pcp port is as follows:
#1 port is 11002
#2 port is 11003
pgpool port is 11000
pcp port is 11001
The info above is in README\&.port\&.

$ ls
README\&.port  bashrc\&.ports  data1  log	   pgpool_reload     run	  startall
archivedir   data0	   etc	  pcppass  pgpool_setup\&.log  shutdownall

$ \&./startall
waiting for server to start\&.\&.\&.\&.11840 2016\-08\-18 13:08:51 JST LOG:  redirecting log output to logging collector process
11840 2016\-08\-18 13:08:51 JST HINT:  Future log output will appear in directory "pg_log"\&.
 done
server started
waiting for server to start\&.\&.\&.\&.11853 2016\-08\-18 13:08:52 JST LOG:  redirecting log output to logging collector process
11853 2016\-08\-18 13:08:52 JST HINT:  Future log output will appear in directory "pg_log"\&.
 done
server started
$ psql \-p 11000 test
Pager usage is off\&.
psql (9\&.5\&.4)
Type "help" for help\&.

test=# show pool_nodes;
 node_id | hostname | port  | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay
\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 0       | /tmp     | 11002 | up     | 0\&.500000  | primary | 0          | false             | 0
 1       | /tmp     | 11003 | up     | 0\&.500000  | standby | 0          | true              | 0
(2 rows)
.fi
.if n \{\
.RE
.\}

