'\" t
.\"     Title: SHOW POOL_POOLS
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: Pgpool-II 3.6.4 文書
.\"    Source: Pgpool-II 3.6.4
.\"  Language: Japanese
.\"
.TH "SHOW POOL_POOLS" "1" "2016" "Pgpool-II 3.6.4" "Pgpool-II 3.6.4 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
SHOW_POOL_POOLS \- Pgpool\-II のコネクションプールの状態を表示する
.SH "概要"
.sp
.nf
SHOW POOL_POOLS
    
.fi
.SH "説明"
.PP
\fBSHOW pool_pools\fR
は
Pgpool\-II
のコネクションプールの状態を表示します。
.PP
11のカラムがあります。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_pid
は
Pgpool\-II
プロセスのプロセス ID です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start_time
はこのプロセスが起動された時刻です (1970年1月1日からの経過秒で表示されます)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_id
はコネクションプール ID です。(0 から
max_pool
\- 1 の値です)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
backend_id
は
PostgreSQL
バックエンドの識別子です(0 からバックエンド数 \- 1 の値です)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
database
はこのプロセスが接続しているデータベース名です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
username
はこのプロセスの接続で使用しているユーザ名です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
create_time
はこの接続が作成された時刻です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
majorversion
と
minorversion
はこの接続で使用されているプロトコルバージョン番号です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_counter
はこの接続が使用された回数です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_backendpid
は
PostgreSQL
のバックエンドプロセスのプロセス ID です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_connected
は真偽値で、0 ならフロントエンドからの接続無し、1 なら接続ありを表します。
.RE
.PP
返却行数は常に
num_init_children
*
max_pool
* 「バックエンドの数」になります。 ここでは例を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
test=# show pool_pools;
 pool_pid |     start_time      | pool_id | backend_id | database | username |     create_time     | majorversion | minorversion | pool_counter | pool_backendpid | pool_connected
\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 19696    | 2016\-10\-17 13:24:17 | 0       | 0          | postgres | t\-ishii  | 2016\-10\-17 13:35:12 | 3            | 0            | 1            | 20079           | 1
 19696    | 2016\-10\-17 13:24:17 | 0       | 1          | postgres | t\-ishii  | 2016\-10\-17 13:35:12 | 3            | 0            | 1            | 20080           | 1
 19696    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19696    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19697    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19698    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19699    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19700    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19701    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19702    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19703    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19704    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19705    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19706    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19707    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19708    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19709    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19710    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19711    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19712    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19713    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19714    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19715    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19716    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19717    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19718    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19719    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19720    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 0       | 0          | test     | t\-ishii  | 2016\-10\-17 14:30:53 | 3            | 0            | 1            | 22055           | 1
 20024    | 2016\-10\-17 13:33:46 | 0       | 1          | test     | t\-ishii  | 2016\-10\-17 14:30:53 | 3            | 0            | 1            | 22056           | 1
 20024    | 2016\-10\-17 13:33:46 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20024    | 2016\-10\-17 13:33:46 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 20600    | 2016\-10\-17 13:46:58 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19723    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19724    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19725    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19726    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 0       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 0       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 1       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 1       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 2       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 2       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 3       | 0          |          |          |                     | 0            | 0            | 0            | 0               | 0
 19727    | 2016\-10\-17 13:24:17 | 3       | 1          |          |          |                     | 0            | 0            | 0            | 0               | 0
(256 rows)
.fi
.if n \{\
.RE
.\}
.sp

