'\" t
.\"     Title: SHOW POOL_PROCESSES
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: Pgpool-II 3.6.4 文書
.\"    Source: Pgpool-II 3.6.4
.\"  Language: Japanese
.\"
.TH "SHOW POOL_PROCESSES" "1" "2016" "Pgpool-II 3.6.4" "Pgpool-II 3.6.4 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
SHOW_POOL_PROCESSES \- 接続待ち、あるいは接続中 Pgpool\-II の子プロセスの状態を表示する
.SH "概要"
.sp
.nf
SHOW POOL_PROCESSES
    
.fi
.SH "説明"
.PP
\fBSHOW POOL_PROCESSES\fR
は接続待ち、あるいは接続中
Pgpool\-II
の子プロセスの状態を表示します。
.PP
6つのカラムがあります。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_pid
は
Pgpool\-II
プロセスのプロセス ID です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start_time
はこのプロセスが起動された時刻です (1970年1月1日からの経過秒で表示されます)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
database
はこのプロセスが接続しているデータベース名です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
username
はこのプロセスの接続で使用しているユーザ名です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
create_time
はこの接続が作成された時刻です。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pool_counter
はこの接続が使用された回数です。
.RE
.PP
ここでは例を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
test=# show pool_processes;
 pool_pid |     start_time      | database | username |     create_time     | pool_counter
\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 19696    | 2016\-10\-17 13:24:17 | postgres | t\-ishii  | 2016\-10\-17 13:35:12 | 1
 19697    | 2016\-10\-17 13:24:17 |          |          |                     |
 19698    | 2016\-10\-17 13:24:17 |          |          |                     |
 19699    | 2016\-10\-17 13:24:17 |          |          |                     |
 19700    | 2016\-10\-17 13:24:17 |          |          |                     |
 19701    | 2016\-10\-17 13:24:17 |          |          |                     |
 19702    | 2016\-10\-17 13:24:17 |          |          |                     |
 19703    | 2016\-10\-17 13:24:17 |          |          |                     |
 19704    | 2016\-10\-17 13:24:17 |          |          |                     |
 19705    | 2016\-10\-17 13:24:17 |          |          |                     |
 19706    | 2016\-10\-17 13:24:17 |          |          |                     |
 19707    | 2016\-10\-17 13:24:17 |          |          |                     |
 19708    | 2016\-10\-17 13:24:17 |          |          |                     |
 19709    | 2016\-10\-17 13:24:17 |          |          |                     |
 19710    | 2016\-10\-17 13:24:17 |          |          |                     |
 19711    | 2016\-10\-17 13:24:17 |          |          |                     |
 19712    | 2016\-10\-17 13:24:17 |          |          |                     |
 19713    | 2016\-10\-17 13:24:17 |          |          |                     |
 19714    | 2016\-10\-17 13:24:17 |          |          |                     |
 19715    | 2016\-10\-17 13:24:17 |          |          |                     |
 19716    | 2016\-10\-17 13:24:17 |          |          |                     |
 19717    | 2016\-10\-17 13:24:17 |          |          |                     |
 19718    | 2016\-10\-17 13:24:17 |          |          |                     |
 19719    | 2016\-10\-17 13:24:17 |          |          |                     |
 19720    | 2016\-10\-17 13:24:17 |          |          |                     |
 20024    | 2016\-10\-17 13:33:46 |          |          |                     |
 19722    | 2016\-10\-17 13:24:17 | test     | t\-ishii  | 2016\-10\-17 13:34:42 | 1
 19723    | 2016\-10\-17 13:24:17 |          |          |                     |
 19724    | 2016\-10\-17 13:24:17 |          |          |                     |
 19725    | 2016\-10\-17 13:24:17 |          |          |                     |
 19726    | 2016\-10\-17 13:24:17 |          |          |                     |
 19727    | 2016\-10\-17 13:24:17 |          |          |                     |
(32 rows)
.fi
.if n \{\
.RE
.\}
.sp

