'\" t
.\"     Title: SHOW POOL NODES
.\"    Author: The Pgpool Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016
.\"    Manual: Pgpool-II 3.6.4 文書
.\"    Source: Pgpool-II 3.6.4
.\"  Language: Japanese
.\"
.TH "SHOW POOL NODES" "1" "2016" "Pgpool-II 3.6.4" "Pgpool-II 3.6.4 文書"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
SHOW_POOL_NODES \- DB ノードのリストを表示する
.SH "概要"
.sp
.nf
SHOW POOL_NODES
    
.fi
.SH "説明"
.PP
\fBSHOW POOL_NODES\fR
はホスト名、ポート番号、状態、 重み(ロードバランスモードで運用しているときにのみ意味があります)、 ノードの役割、発行された SELECT の数、ロードバランスノードであるかどうか、 レプリケーション遅延 (ストリーミングレプリケーションモードのみ) が表示されます。 状態(status)の意味については、
\fBpcp_node_info\fR(1)
リファレンスで説明されています。 ホスト名が "/tmp" のように表示される場合、UNIX ドメインソケットを使用して
Pgpool\-II
が
PostgreSQL
に接続していることを意味します。 SELECT の数には、Pgpool\-II
内部で発行されるクエリの数は含まれません。 また、このカウンタは
Pgpool\-II
がスタートした時に 0にリセットされます。
.PP
ここでは例を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
test=# show pool_nodes;
 node_id | hostname | port  | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay
\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 0       | /tmp     | 11002 | up     | 0\&.500000  | primary | 0          | false             | 0
 1       | /tmp     | 11003 | up     | 0\&.500000  | standby | 0          | true              | 0
(2 rows)
.fi
.if n \{\
.RE
.\}
.sp

